//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalRiver.CloudLink.Commerce.Nimbus.ViewModels.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DigitalRiver.CloudLink.Commerce.Nimbus.ViewModels.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupon code may not be longer than 20 characters..
        /// </summary>
        public static string AddCouponModel_CouponCodeInvalid {
            get {
                return ResourceManager.GetString("AddCouponModel_CouponCodeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a coupon code..
        /// </summary>
        public static string AddCouponModel_CouponCodeMissing {
            get {
                return ResourceManager.GetString("AddCouponModel_CouponCodeMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a product to add..
        /// </summary>
        public static string AddProductModel_ProductIdMissing {
            get {
                return ResourceManager.GetString("AddProductModel_ProductIdMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an item to update..
        /// </summary>
        public static string ChangeVariationModel_LineItemIdMissing {
            get {
                return ResourceManager.GetString("ChangeVariationModel_LineItemIdMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a product to update..
        /// </summary>
        public static string ChangeVariationModel_ProductIdMissing {
            get {
                return ResourceManager.GetString("ChangeVariationModel_ProductIdMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Address.
        /// </summary>
        public static string PaymentModel_AddressId {
            get {
                return ResourceManager.GetString("PaymentModel_AddressId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the billing address..
        /// </summary>
        public static string PaymentModel_AddressIdMissing {
            get {
                return ResourceManager.GetString("PaymentModel_AddressIdMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration Month.
        /// </summary>
        public static string PaymentModel_ExpirationMonth {
            get {
                return ResourceManager.GetString("PaymentModel_ExpirationMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the expiration month on the credit card..
        /// </summary>
        public static string PaymentModel_ExpirationMonthMissing {
            get {
                return ResourceManager.GetString("PaymentModel_ExpirationMonthMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration Year.
        /// </summary>
        public static string PaymentModel_ExpirationYear {
            get {
                return ResourceManager.GetString("PaymentModel_ExpirationYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the expiration year on the credit card..
        /// </summary>
        public static string PaymentModel_ExpirationYearMissing {
            get {
                return ResourceManager.GetString("PaymentModel_ExpirationYearMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name On Card.
        /// </summary>
        public static string PaymentModel_Name {
            get {
                return ResourceManager.GetString("PaymentModel_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name must be alphabetic characters only..
        /// </summary>
        public static string PaymentModel_NameInvalid {
            get {
                return ResourceManager.GetString("PaymentModel_NameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the name on the card..
        /// </summary>
        public static string PaymentModel_NameMissing {
            get {
                return ResourceManager.GetString("PaymentModel_NameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Nickname.
        /// </summary>
        public static string PaymentModel_Nickname {
            get {
                return ResourceManager.GetString("PaymentModel_Nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nickname name must be alphabetic  characters only..
        /// </summary>
        public static string PaymentModel_NicknameInvalid {
            get {
                return ResourceManager.GetString("PaymentModel_NicknameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a nickname for this payment. (eg. My Visa Card).
        /// </summary>
        public static string PaymentModel_NicknameMissing {
            get {
                return ResourceManager.GetString("PaymentModel_NicknameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Number.
        /// </summary>
        public static string PaymentModel_Number {
            get {
                return ResourceManager.GetString("PaymentModel_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid credit card number..
        /// </summary>
        public static string PaymentModel_NumberInvalid {
            get {
                return ResourceManager.GetString("PaymentModel_NumberInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the number on the credit card..
        /// </summary>
        public static string PaymentModel_NumberMissing {
            get {
                return ResourceManager.GetString("PaymentModel_NumberMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Code.
        /// </summary>
        public static string PaymentModel_SecurityCode {
            get {
                return ResourceManager.GetString("PaymentModel_SecurityCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security code must be numeric..
        /// </summary>
        public static string PaymentModel_SecurityCodeInvalid {
            get {
                return ResourceManager.GetString("PaymentModel_SecurityCodeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the security code on the credit card..
        /// </summary>
        public static string PaymentModel_SecurityCodeMissing {
            get {
                return ResourceManager.GetString("PaymentModel_SecurityCodeMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an item to update..
        /// </summary>
        public static string UpdateLineItemModel_LineItemIdMissing {
            get {
                return ResourceManager.GetString("UpdateLineItemModel_LineItemIdMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a quantity for the item..
        /// </summary>
        public static string UpdateLineItemModel_QuantityMissing {
            get {
                return ResourceManager.GetString("UpdateLineItemModel_QuantityMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid quantity for the item..
        /// </summary>
        public static string UpdateLineItemModel_QuantityTooSmall {
            get {
                return ResourceManager.GetString("UpdateLineItemModel_QuantityTooSmall", resourceCulture);
            }
        }
    }
}
