//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalRiver.CloudLink.Commerce.Nimbus.SportsUs.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DigitalRiver.CloudLink.Commerce.Nimbus.SportsUs.Resources.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you are not old enough to watch this content..
        /// </summary>
        public static string AgeGate_AgeRestrictedContent {
            get {
                return ResourceManager.GetString("AgeGate_AgeRestrictedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your date of birth..
        /// </summary>
        public static string AgeGate_VerifyBirthDate {
            get {
                return ResourceManager.GetString("AgeGate_VerifyBirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re sorry but an invalid date was selected. Please select a valid date and try again..
        /// </summary>
        public static string Catalog_AgeGateDateInvalid {
            get {
                return ResourceManager.GetString("Catalog_AgeGateDateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Catalog_CatalogHomeName {
            get {
                return ResourceManager.GetString("Catalog_CatalogHomeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did you mean.
        /// </summary>
        public static string Catalog_CatalogSearchDidYouMean {
            get {
                return ResourceManager.GetString("Catalog_CatalogSearchDidYouMean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        public static string Catalog_CatalogSearchDidYouMeanQuestionMark {
            get {
                return ResourceManager.GetString("Catalog_CatalogSearchDidYouMeanQuestionMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results were found for: &quot;{0}&quot;.
        /// </summary>
        public static string Catalog_CatalogSearchNoResultsFoundFor {
            get {
                return ResourceManager.GetString("Catalog_CatalogSearchNoResultsFoundFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset all filters.
        /// </summary>
        public static string Catalog_CatalogSearchResetAllFilters {
            get {
                return ResourceManager.GetString("Catalog_CatalogSearchResetAllFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refine your results.
        /// </summary>
        public static string Catalog_CatalogSearchResultsFiltersHeading {
            get {
                return ResourceManager.GetString("Catalog_CatalogSearchResultsFiltersHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find what you want? We&apos;re here to help..
        /// </summary>
        public static string Catalog_CatalogSearchResultsSupportMessage {
            get {
                return ResourceManager.GetString("Catalog_CatalogSearchResultsSupportMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1-800-598-7450.
        /// </summary>
        public static string Catalog_CatalogSearchResultsSupportPhone {
            get {
                return ResourceManager.GetString("Catalog_CatalogSearchResultsSupportPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search results for.
        /// </summary>
        public static string Catalog_CatalogSearchResultsTitle {
            get {
                return ResourceManager.GetString("Catalog_CatalogSearchResultsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading... %lt;span class=&quot;currentPageStart&quot;%gt;{0}%lt;/span%gt;-%lt;span class=&quot;currentPageEnd&quot;%gt;{1}%lt;/span%gt; of {2} Results.
        /// </summary>
        public static string Catalog_LoadingXThroughYOfZResults {
            get {
                return ResourceManager.GetString("Catalog_LoadingXThroughYOfZResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, no products were found..
        /// </summary>
        public static string Catalog_NoProductsFound {
            get {
                return ResourceManager.GetString("Catalog_NoProductsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, the product does not exist..
        /// </summary>
        public static string Catalog_ProductNotFound {
            get {
                return ResourceManager.GetString("Catalog_ProductNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search results:.
        /// </summary>
        public static string Catalog_SearchResultsColon {
            get {
                return ResourceManager.GetString("Catalog_SearchResultsColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop these {0} categories.
        /// </summary>
        public static string Catalog_ShopTheseCategoriesColon {
            get {
                return ResourceManager.GetString("Catalog_ShopTheseCategoriesColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viewing .
        /// </summary>
        public static string Catalog_ViewingOneThroughXOfYResultsPart1 {
            get {
                return ResourceManager.GetString("Catalog_ViewingOneThroughXOfYResultsPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  of .
        /// </summary>
        public static string Catalog_ViewingOneThroughXOfYResultsPart2 {
            get {
                return ResourceManager.GetString("Catalog_ViewingOneThroughXOfYResultsPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Results.
        /// </summary>
        public static string Catalog_ViewingOneThroughXOfYResultsPart3 {
            get {
                return ResourceManager.GetString("Catalog_ViewingOneThroughXOfYResultsPart3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping Cart..
        /// </summary>
        public static string Checkout_Cart {
            get {
                return ResourceManager.GetString("Checkout_Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Shopping Cart is Empty..
        /// </summary>
        public static string Checkout_CartIsEmpty {
            get {
                return ResourceManager.GetString("Checkout_CartIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue Shopping.
        /// </summary>
        public static string Checkout_ContinueShopping {
            get {
                return ResourceManager.GetString("Checkout_ContinueShopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.credit-card-logos.com/images/multiple_credit-card-logos-1/credit_card_logos_22.gif.
        /// </summary>
        public static string Checkout_PaymentOptionsImage {
            get {
                return ResourceManager.GetString("Checkout_PaymentOptionsImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment options.
        /// </summary>
        public static string Checkout_PaymentOptionsText {
            get {
                return ResourceManager.GetString("Checkout_PaymentOptionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promo Code:.
        /// </summary>
        public static string Checkout_PromoCodeColon {
            get {
                return ResourceManager.GetString("Checkout_PromoCodeColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verizon Secured.
        /// </summary>
        public static string Checkout_VerizonSecured {
            get {
                return ResourceManager.GetString("Checkout_VerizonSecured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to before taxes.
        /// </summary>
        public static string CheckoutTotals_BeforeTaxes {
            get {
                return ResourceManager.GetString("CheckoutTotals_BeforeTaxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount:.
        /// </summary>
        public static string CheckoutTotals_DiscountColon {
            get {
                return ResourceManager.GetString("CheckoutTotals_DiscountColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtotal:.
        /// </summary>
        public static string CheckoutTotals_SubtotalBeforeTaxesColon {
            get {
                return ResourceManager.GetString("CheckoutTotals_SubtotalBeforeTaxesColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to cart.
        /// </summary>
        public static string CustomBundles_AddToCart {
            get {
                return ResourceManager.GetString("CustomBundles_AddToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternate image.
        /// </summary>
        public static string CustomBundles_AlternateImage {
            get {
                return ResourceManager.GetString("CustomBundles_AlternateImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to check mark.
        /// </summary>
        public static string CustomBundles_CheckMark {
            get {
                return ResourceManager.GetString("CustomBundles_CheckMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CustomBundles_Close {
            get {
                return ResourceManager.GetString("CustomBundles_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue shopping.
        /// </summary>
        public static string CustomBundles_ContinueShopping {
            get {
                return ResourceManager.GetString("CustomBundles_ContinueShopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish Your Bundle.
        /// </summary>
        public static string CustomBundles_FinishYourBundle {
            get {
                return ResourceManager.GetString("CustomBundles_FinishYourBundle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found.
        /// </summary>
        public static string CustomBundles_NotFound {
            get {
                return ResourceManager.GetString("CustomBundles_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of stock.
        /// </summary>
        public static string CustomBundles_OutOfStock {
            get {
                return ResourceManager.GetString("CustomBundles_OutOfStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;ve automatically added these products for you..
        /// </summary>
        public static string CustomBundles_PidsPreselected {
            get {
                return ResourceManager.GetString("CustomBundles_PidsPreselected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-Order.
        /// </summary>
        public static string CustomBundles_Preorder {
            get {
                return ResourceManager.GetString("CustomBundles_Preorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick look.
        /// </summary>
        public static string CustomBundles_QuickLook {
            get {
                return ResourceManager.GetString("CustomBundles_QuickLook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick View.
        /// </summary>
        public static string CustomBundles_QuickView {
            get {
                return ResourceManager.GetString("CustomBundles_QuickView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string CustomBundles_Remove {
            get {
                return ResourceManager.GetString("CustomBundles_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Your Bundle.
        /// </summary>
        public static string CustomBundles_ReviewYourBundle {
            get {
                return ResourceManager.GetString("CustomBundles_ReviewYourBundle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string CustomBundles_Select {
            get {
                return ResourceManager.GetString("CustomBundles_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a required product.
        /// </summary>
        public static string CustomBundles_SelectARequiredProduct {
            get {
                return ResourceManager.GetString("CustomBundles_SelectARequiredProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected.
        /// </summary>
        public static string CustomBundles_Selected {
            get {
                return ResourceManager.GetString("CustomBundles_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show fewer products.
        /// </summary>
        public static string CustomBundles_ShowFewerProducts {
            get {
                return ResourceManager.GetString("CustomBundles_ShowFewerProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show more products.
        /// </summary>
        public static string CustomBundles_ShowMoreProducts {
            get {
                return ResourceManager.GetString("CustomBundles_ShowMoreProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This bundle is not currently available..
        /// </summary>
        public static string CustomBundles_UnableToFindBundle {
            get {
                return ResourceManager.GetString("CustomBundles_UnableToFindBundle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to was.
        /// </summary>
        public static string CustomBundles_Was {
            get {
                return ResourceManager.GetString("CustomBundles_Was", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to April.
        /// </summary>
        public static string Date_April {
            get {
                return ResourceManager.GetString("Date_April", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to August.
        /// </summary>
        public static string Date_August {
            get {
                return ResourceManager.GetString("Date_August", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string Date_Day {
            get {
                return ResourceManager.GetString("Date_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to December.
        /// </summary>
        public static string Date_December {
            get {
                return ResourceManager.GetString("Date_December", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to February.
        /// </summary>
        public static string Date_February {
            get {
                return ResourceManager.GetString("Date_February", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to January.
        /// </summary>
        public static string Date_January {
            get {
                return ResourceManager.GetString("Date_January", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to July.
        /// </summary>
        public static string Date_July {
            get {
                return ResourceManager.GetString("Date_July", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to June.
        /// </summary>
        public static string Date_June {
            get {
                return ResourceManager.GetString("Date_June", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to March.
        /// </summary>
        public static string Date_March {
            get {
                return ResourceManager.GetString("Date_March", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May.
        /// </summary>
        public static string Date_May {
            get {
                return ResourceManager.GetString("Date_May", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Date_Month {
            get {
                return ResourceManager.GetString("Date_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to November.
        /// </summary>
        public static string Date_November {
            get {
                return ResourceManager.GetString("Date_November", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to October.
        /// </summary>
        public static string Date_October {
            get {
                return ResourceManager.GetString("Date_October", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to September.
        /// </summary>
        public static string Date_September {
            get {
                return ResourceManager.GetString("Date_September", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Date_Year {
            get {
                return ResourceManager.GetString("Date_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, JavaScript must be enabled to view this page..
        /// </summary>
        public static string Error_JavascriptDisabledError {
            get {
                return ResourceManager.GetString("Error_JavascriptDisabledError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are currently experiencing problems. Please try again later..
        /// </summary>
        public static string Error_WeAreCurrentlyExperiencingProblems {
            get {
                return ResourceManager.GetString("Error_WeAreCurrentlyExperiencingProblems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, an error occurred while processing your request..
        /// </summary>
        public static string ErrorCode_ErrorOccurred {
            get {
                return ResourceManager.GetString("ErrorCode_ErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an issue processing your order requiring automatic logout. Please contact 1-800-598-7450 for assistance in completing your purchase. Error Code: {0}.
        /// </summary>
        public static string ErrorCode_ErrorProcessingOrder {
            get {
                return ResourceManager.GetString("ErrorCode_ErrorProcessingOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an issue processing your order. Your credit card has expired. You will need to update credit card information or use a different payment method to proceed with checkout. Error Code: {0}.
        /// </summary>
        public static string ErrorCode_ErrorProcessingOrderExpiredCard {
            get {
                return ResourceManager.GetString("ErrorCode_ErrorProcessingOrderExpiredCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an issue processing your order requiring automatic logout. You will need to login again to proceeed with checkout. Error Code: {0}.
        /// </summary>
        public static string ErrorCode_ErrorProcessingOrderNewBrowser {
            get {
                return ResourceManager.GetString("ErrorCode_ErrorProcessingOrderNewBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an issue processing your order requiring automatic logout. You will need to login again and use a different payment method to proceed with checkout. Error Code: {0}.
        /// </summary>
        public static string ErrorCode_ErrorProcessingOrderNewBrowserDifferentPayment {
            get {
                return ResourceManager.GetString("ErrorCode_ErrorProcessingOrderNewBrowserDifferentPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an issue processing your order requiring automatic logout. You will need to login again and use a different payment method to proceed with checkout. Error Code: {0}.
        /// </summary>
        public static string ErrorCode_ErrorProcessingOrderTooManyItemsInCart {
            get {
                return ResourceManager.GetString("ErrorCode_ErrorProcessingOrderTooManyItemsInCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to field error.
        /// </summary>
        public static string ErrorCode_FieldError {
            get {
                return ResourceManager.GetString("ErrorCode_FieldError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found.
        /// </summary>
        public static string ErrorCode_NotFound {
            get {
                return ResourceManager.GetString("ErrorCode_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please review the information below and fill in all required fields.
        /// </summary>
        public static string ErrorCode_RequiredFieldsMissing {
            get {
                return ResourceManager.GetString("ErrorCode_RequiredFieldsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required..
        /// </summary>
        public static string ErrorCode_ThisFieldIsRequired {
            get {
                return ResourceManager.GetString("ErrorCode_ThisFieldIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We were unable to find the item you requested..
        /// </summary>
        public static string ErrorCode_UnableToFindRequestedItem {
            get {
                return ResourceManager.GetString("ErrorCode_UnableToFindRequestedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string FormActions_Add {
            get {
                return ResourceManager.GetString("FormActions_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new address.
        /// </summary>
        public static string FormActions_AddAddress {
            get {
                return ResourceManager.GetString("FormActions_AddAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string FormActions_Apply {
            get {
                return ResourceManager.GetString("FormActions_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string FormActions_Cancel {
            get {
                return ResourceManager.GetString("FormActions_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel edit address.
        /// </summary>
        public static string FormActions_CancelEditAddress {
            get {
                return ResourceManager.GetString("FormActions_CancelEditAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string FormActions_Change {
            get {
                return ResourceManager.GetString("FormActions_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}:.
        /// </summary>
        public static string FormActions_ColonFieldsMarkFormat {
            get {
                return ResourceManager.GetString("FormActions_ColonFieldsMarkFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string FormActions_Continue {
            get {
                return ResourceManager.GetString("FormActions_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string FormActions_Delete {
            get {
                return ResourceManager.GetString("FormActions_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string FormActions_Edit {
            get {
                return ResourceManager.GetString("FormActions_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit address.
        /// </summary>
        public static string FormActions_EditAddress {
            get {
                return ResourceManager.GetString("FormActions_EditAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit payment information.
        /// </summary>
        public static string FormActions_EditPaymentInformation {
            get {
                return ResourceManager.GetString("FormActions_EditPaymentInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit shipping method.
        /// </summary>
        public static string FormActions_EditShippingMethod {
            get {
                return ResourceManager.GetString("FormActions_EditShippingMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates required fields.
        /// </summary>
        public static string FormActions_IndicatesRequiredFields {
            get {
                return ResourceManager.GetString("FormActions_IndicatesRequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make default.
        /// </summary>
        public static string FormActions_MakeDefault {
            get {
                return ResourceManager.GetString("FormActions_MakeDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        public static string FormActions_RequiredFieldsMark {
            get {
                return ResourceManager.GetString("FormActions_RequiredFieldsMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1}{2}{3}.
        /// </summary>
        public static string FormActions_RequiredFieldsMarkFormat {
            get {
                return ResourceManager.GetString("FormActions_RequiredFieldsMarkFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string FormActions_Save {
            get {
                return ResourceManager.GetString("FormActions_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save new address.
        /// </summary>
        public static string FormActions_SaveNewAddress {
            get {
                return ResourceManager.GetString("FormActions_SaveNewAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string FormActions_SelectOption {
            get {
                return ResourceManager.GetString("FormActions_SelectOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string FormActions_Submit {
            get {
                return ResourceManager.GetString("FormActions_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string General_Address {
            get {
                return ResourceManager.GetString("General_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart Items.
        /// </summary>
        public static string General_CartItems {
            get {
                return ResourceManager.GetString("General_CartItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to play the video.
        /// </summary>
        public static string General_ClickToPlay {
            get {
                return ResourceManager.GetString("General_ClickToPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string General_Close {
            get {
                return ResourceManager.GetString("General_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $.
        /// </summary>
        public static string General_Currency {
            get {
                return ResourceManager.GetString("General_Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequently asked questions.
        /// </summary>
        public static string General_FrequentlyAskedQuestions {
            get {
                return ResourceManager.GetString("General_FrequentlyAskedQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string General_Help {
            get {
                return ResourceManager.GetString("General_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string General_Home {
            get {
                return ResourceManager.GetString("General_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This site is hosted by Digital River.
        /// </summary>
        public static string General_HostedByDr {
            get {
                return ResourceManager.GetString("General_HostedByDr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading images....
        /// </summary>
        public static string General_LoadingImages {
            get {
                return ResourceManager.GetString("General_LoadingImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string General_Menu {
            get {
                return ResourceManager.GetString("General_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need help?.
        /// </summary>
        public static string General_NeedHelpQuestion {
            get {
                return ResourceManager.GetString("General_NeedHelpQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        public static string General_PleaseWait {
            get {
                return ResourceManager.GetString("General_PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print subscription details.
        /// </summary>
        public static string General_PrintSubscriptionDetails {
            get {
                return ResourceManager.GetString("General_PrintSubscriptionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity:.
        /// </summary>
        public static string General_QuantityColon {
            get {
                return ResourceManager.GetString("General_QuantityColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to top.
        /// </summary>
        public static string General_ReturnToTop {
            get {
                return ResourceManager.GetString("General_ReturnToTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search SportsUs.
        /// </summary>
        public static string General_Search {
            get {
                return ResourceManager.GetString("General_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string General_SearchButtonText {
            get {
                return ResourceManager.GetString("General_SearchButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Error - Sports US.
        /// </summary>
        public static string General_ServerErrorPageTitle {
            get {
                return ResourceManager.GetString("General_ServerErrorPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SportsUS.
        /// </summary>
        public static string General_Store {
            get {
                return ResourceManager.GetString("General_Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SportsUS Home.
        /// </summary>
        public static string General_StoreHome {
            get {
                return ResourceManager.GetString("General_StoreHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SportsUS Online Store.
        /// </summary>
        public static string General_StoreOnline {
            get {
                return ResourceManager.GetString("General_StoreOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SportsUS Online Store.
        /// </summary>
        public static string General_StoreTitle {
            get {
                return ResourceManager.GetString("General_StoreTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of Use And Sale.
        /// </summary>
        public static string General_TermsOfUseAndSale {
            get {
                return ResourceManager.GetString("General_TermsOfUseAndSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Navigation.
        /// </summary>
        public static string General_ToggleNavigation {
            get {
                return ResourceManager.GetString("General_ToggleNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Search.
        /// </summary>
        public static string General_ToggleSearch {
            get {
                return ResourceManager.GetString("General_ToggleSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to SportsUS Online Store.
        /// </summary>
        public static string General_WelcomeToOurStore {
            get {
                return ResourceManager.GetString("General_WelcomeToOurStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided Offer ID not available for shopper.
        /// </summary>
        public static string GetOffersException_OfferNotFound {
            get {
                return ResourceManager.GetString("GetOffersException_OfferNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product not found for provided product key.
        /// </summary>
        public static string GetOffersException_ProductNotFound {
            get {
                return ResourceManager.GetString("GetOffersException_ProductNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Statement.
        /// </summary>
        public static string Help_PrivacyStatement {
            get {
                return ResourceManager.GetString("Help_PrivacyStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms Of Use and Sale.
        /// </summary>
        public static string Help_TermsOfUseAndSale {
            get {
                return ResourceManager.GetString("Help_TermsOfUseAndSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *before applicable taxes.
        /// </summary>
        public static string InvoiceViewModel_BeforeApplicableTaxes {
            get {
                return ResourceManager.GetString("InvoiceViewModel_BeforeApplicableTaxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Address:.
        /// </summary>
        public static string InvoiceViewModel_BillingAddress {
            get {
                return ResourceManager.GetString("InvoiceViewModel_BillingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Address:.
        /// </summary>
        public static string InvoiceViewModel_BillingAddressColon {
            get {
                return ResourceManager.GetString("InvoiceViewModel_BillingAddressColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill to.
        /// </summary>
        public static string InvoiceViewModel_BillTo {
            get {
                return ResourceManager.GetString("InvoiceViewModel_BillTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking on possible download link....
        /// </summary>
        public static string InvoiceViewModel_CheckingOnPossibleDownloadLink {
            get {
                return ResourceManager.GetString("InvoiceViewModel_CheckingOnPossibleDownloadLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue shopping.
        /// </summary>
        public static string InvoiceViewModel_ContinueShopping {
            get {
                return ResourceManager.GetString("InvoiceViewModel_ContinueShopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery method: .
        /// </summary>
        public static string InvoiceViewModel_DeliveryMethod {
            get {
                return ResourceManager.GetString("InvoiceViewModel_DeliveryMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount:.
        /// </summary>
        public static string InvoiceViewModel_Discount {
            get {
                return ResourceManager.GetString("InvoiceViewModel_Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string InvoiceViewModel_Download {
            get {
                return ResourceManager.GetString("InvoiceViewModel_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email: .
        /// </summary>
        public static string InvoiceViewModel_Email {
            get {
                return ResourceManager.GetString("InvoiceViewModel_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        public static string InvoiceViewModel_EmailColon {
            get {
                return ResourceManager.GetString("InvoiceViewModel_EmailColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ending in .
        /// </summary>
        public static string InvoiceViewModel_EndingIn {
            get {
                return ResourceManager.GetString("InvoiceViewModel_EndingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated ship date: .
        /// </summary>
        public static string InvoiceViewModel_EstimatedShipDate {
            get {
                return ResourceManager.GetString("InvoiceViewModel_EstimatedShipDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated Ship Date:.
        /// </summary>
        public static string InvoiceViewModel_EstimatedShipDateColon {
            get {
                return ResourceManager.GetString("InvoiceViewModel_EstimatedShipDateColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eWaste Fee.
        /// </summary>
        public static string InvoiceViewModel_EwasteFee {
            get {
                return ResourceManager.GetString("InvoiceViewModel_EwasteFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eWaste Fee Documentation.
        /// </summary>
        public static string InvoiceViewModel_EwasteFeeDocumentation {
            get {
                return ResourceManager.GetString("InvoiceViewModel_EwasteFeeDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /sportsus/en-us/home.
        /// </summary>
        public static string InvoiceViewModel_EwasteFeeUrl {
            get {
                return ResourceManager.GetString("InvoiceViewModel_EwasteFeeUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration Date: .
        /// </summary>
        public static string InvoiceViewModel_ExpirationDate {
            get {
                return ResourceManager.GetString("InvoiceViewModel_ExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration Date:.
        /// </summary>
        public static string InvoiceViewModel_ExpirationDateColon {
            get {
                return ResourceManager.GetString("InvoiceViewModel_ExpirationDateColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install/Manage.
        /// </summary>
        public static string InvoiceViewModel_InstallManage {
            get {
                return ResourceManager.GetString("InvoiceViewModel_InstallManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please see your confirmation email for additional information.
        /// </summary>
        public static string InvoiceViewModel_LineItemPromoCodeTypeInstructions {
            get {
                return ResourceManager.GetString("InvoiceViewModel_LineItemPromoCodeTypeInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string InvoiceViewModel_Order {
            get {
                return ResourceManager.GetString("InvoiceViewModel_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order date: .
        /// </summary>
        public static string InvoiceViewModel_OrderDate {
            get {
                return ResourceManager.GetString("InvoiceViewModel_OrderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order date:.
        /// </summary>
        public static string InvoiceViewModel_OrderDateColon {
            get {
                return ResourceManager.GetString("InvoiceViewModel_OrderDateColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order discount:.
        /// </summary>
        public static string InvoiceViewModel_OrderDiscountColon {
            get {
                return ResourceManager.GetString("InvoiceViewModel_OrderDiscountColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order #: .
        /// </summary>
        public static string InvoiceViewModel_OrderNum {
            get {
                return ResourceManager.GetString("InvoiceViewModel_OrderNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order number: .
        /// </summary>
        public static string InvoiceViewModel_OrderNumber {
            get {
                return ResourceManager.GetString("InvoiceViewModel_OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order number:.
        /// </summary>
        public static string InvoiceViewModel_OrderNumberColon {
            get {
                return ResourceManager.GetString("InvoiceViewModel_OrderNumberColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        public static string InvoiceViewModel_OrderStatusColon {
            get {
                return ResourceManager.GetString("InvoiceViewModel_OrderStatusColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order total:.
        /// </summary>
        public static string InvoiceViewModel_OrderTotalColon {
            get {
                return ResourceManager.GetString("InvoiceViewModel_OrderTotalColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment:.
        /// </summary>
        public static string InvoiceViewModel_Payment {
            get {
                return ResourceManager.GetString("InvoiceViewModel_Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment:.
        /// </summary>
        public static string InvoiceViewModel_PaymentColon {
            get {
                return ResourceManager.GetString("InvoiceViewModel_PaymentColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-Order.
        /// </summary>
        public static string InvoiceViewModel_PreOrder {
            get {
                return ResourceManager.GetString("InvoiceViewModel_PreOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Key: .
        /// </summary>
        public static string InvoiceViewModel_ProductKey {
            get {
                return ResourceManager.GetString("InvoiceViewModel_ProductKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchasing Information.
        /// </summary>
        public static string InvoiceViewModel_PurchasingInformation {
            get {
                return ResourceManager.GetString("InvoiceViewModel_PurchasingInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty: .
        /// </summary>
        public static string InvoiceViewModel_Qty {
            get {
                return ResourceManager.GetString("InvoiceViewModel_Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping:.
        /// </summary>
        public static string InvoiceViewModel_Shipping {
            get {
                return ResourceManager.GetString("InvoiceViewModel_Shipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Method:.
        /// </summary>
        public static string InvoiceViewModel_ShippingMethod {
            get {
                return ResourceManager.GetString("InvoiceViewModel_ShippingMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Method:.
        /// </summary>
        public static string InvoiceViewModel_ShippingMethodColon {
            get {
                return ResourceManager.GetString("InvoiceViewModel_ShippingMethodColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship to.
        /// </summary>
        public static string InvoiceViewModel_ShipTo {
            get {
                return ResourceManager.GetString("InvoiceViewModel_ShipTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship-To Address:.
        /// </summary>
        public static string InvoiceViewModel_ShipToAddress {
            get {
                return ResourceManager.GetString("InvoiceViewModel_ShipToAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship-To Address:.
        /// </summary>
        public static string InvoiceViewModel_ShipToAddressColon {
            get {
                return ResourceManager.GetString("InvoiceViewModel_ShipToAddressColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtotal:.
        /// </summary>
        public static string InvoiceViewModel_Subtotal {
            get {
                return ResourceManager.GetString("InvoiceViewModel_Subtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtotal:*.
        /// </summary>
        public static string InvoiceViewModel_SubtotalColnAst {
            get {
                return ResourceManager.GetString("InvoiceViewModel_SubtotalColnAst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Subtotal includes California .
        /// </summary>
        public static string InvoiceViewModel_SubtotalIncludesCalifornia {
            get {
                return ResourceManager.GetString("InvoiceViewModel_SubtotalIncludesCalifornia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax:.
        /// </summary>
        public static string InvoiceViewModel_Tax {
            get {
                return ResourceManager.GetString("InvoiceViewModel_Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you!.
        /// </summary>
        public static string InvoiceViewModel_ThankYou {
            get {
                return ResourceManager.GetString("InvoiceViewModel_ThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your order.
        /// </summary>
        public static string InvoiceViewModel_ThankYouForYourOrder {
            get {
                return ResourceManager.GetString("InvoiceViewModel_ThankYouForYourOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your order.
        /// </summary>
        public static string InvoiceViewModel_ThankYouMessaging {
            get {
                return ResourceManager.GetString("InvoiceViewModel_ThankYouMessaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total:.
        /// </summary>
        public static string InvoiceViewModel_Total {
            get {
                return ResourceManager.GetString("InvoiceViewModel_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View instructions.
        /// </summary>
        public static string InvoiceViewModel_ViewInstructions {
            get {
                return ResourceManager.GetString("InvoiceViewModel_ViewInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %lt;br /%gt;We&apos;ve sent your receipt and any related instructions to: .
        /// </summary>
        public static string InvoiceViewModel_WeveSentYourReceiptAndAnyRelatedInstructionsTo {
            get {
                return ResourceManager.GetString("InvoiceViewModel_WeveSentYourReceiptAndAnyRelatedInstructionsTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your order number: .
        /// </summary>
        public static string InvoiceViewModel_YourOrderNumber {
            get {
                return ResourceManager.GetString("InvoiceViewModel_YourOrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart.
        /// </summary>
        public static string MiniCart_Cart {
            get {
                return ResourceManager.GetString("MiniCart_Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout.
        /// </summary>
        public static string MiniCart_Checkout {
            get {
                return ResourceManager.GetString("MiniCart_Checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SportsUS - Shop {CategoryName}.
        /// </summary>
        public static string PageTitle_Category {
            get {
                return ResourceManager.GetString("PageTitle_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SportsUS - Shop for all your sports equipment online.
        /// </summary>
        public static string PageTitle_PagetypeAllOthers {
            get {
                return ResourceManager.GetString("PageTitle_PagetypeAllOthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SportsUS - Search Results.
        /// </summary>
        public static string PageTitle_PagetypeSearchResults {
            get {
                return ResourceManager.GetString("PageTitle_PagetypeSearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SportsUS - Shopping Cart.
        /// </summary>
        public static string PageTitle_PagetypeShoppingCart {
            get {
                return ResourceManager.GetString("PageTitle_PagetypeShoppingCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SportsUS - Buy {ProductName}.
        /// </summary>
        public static string PageTitle_Product {
            get {
                return ResourceManager.GetString("PageTitle_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to play the video.
        /// </summary>
        public static string Parts_ClickToPlayVideo {
            get {
                return ResourceManager.GetString("Parts_ClickToPlayVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll left.
        /// </summary>
        public static string Parts_ScrollLeft {
            get {
                return ResourceManager.GetString("Parts_ScrollLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll right.
        /// </summary>
        public static string Parts_ScrollRight {
            get {
                return ResourceManager.GetString("Parts_ScrollRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string PaymentMethodsList_Edit {
            get {
                return ResourceManager.GetString("PaymentMethodsList_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ending in .
        /// </summary>
        public static string PaymentMethodsList_EndingIn {
            get {
                return ResourceManager.GetString("PaymentMethodsList_EndingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expires .
        /// </summary>
        public static string PaymentMethodsList_Expires {
            get {
                return ResourceManager.GetString("PaymentMethodsList_Expires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay with:.
        /// </summary>
        public static string PaymentMethodsList_PayWith {
            get {
                return ResourceManager.GetString("PaymentMethodsList_PayWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay with PayPal.
        /// </summary>
        public static string PaymentMethodsList_PayWithPaypal {
            get {
                return ResourceManager.GetString("PaymentMethodsList_PayWithPaypal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay with this card.
        /// </summary>
        public static string PaymentMethodsList_PayWithThisCard {
            get {
                return ResourceManager.GetString("PaymentMethodsList_PayWithThisCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to incl. GST.
        /// </summary>
        public static string PriceViewModel_Vatnotification {
            get {
                return ResourceManager.GetString("PriceViewModel_Vatnotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 360-view.
        /// </summary>
        public static string Product_360View {
            get {
                return ResourceManager.GetString("Product_360View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Product_Add {
            get {
                return ResourceManager.GetString("Product_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added.
        /// </summary>
        public static string Product_Added {
            get {
                return ResourceManager.GetString("Product_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to added to your cart.
        /// </summary>
        public static string Product_AddedToCart {
            get {
                return ResourceManager.GetString("Product_AddedToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding to cart.
        /// </summary>
        public static string Product_AddingToCart {
            get {
                return ResourceManager.GetString("Product_AddingToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to cart.
        /// </summary>
        public static string Product_AddToCart {
            get {
                return ResourceManager.GetString("Product_AddToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color:.
        /// </summary>
        public static string Product_ColorColon {
            get {
                return ResourceManager.GetString("Product_ColorColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery method:.
        /// </summary>
        public static string Product_DeliveryMethodColon {
            get {
                return ResourceManager.GetString("Product_DeliveryMethodColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated ship date:.
        /// </summary>
        public static string Product_EstimatedShipDateColon {
            get {
                return ResourceManager.GetString("Product_EstimatedShipDateColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For 2 PCs.
        /// </summary>
        public static string Product_For2Pcs {
            get {
                return ResourceManager.GetString("Product_For2Pcs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For 2 PCs or Macs.
        /// </summary>
        public static string Product_For2PcsOrMacs {
            get {
                return ResourceManager.GetString("Product_For2PcsOrMacs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For one Mac.
        /// </summary>
        public static string Product_ForOneMac {
            get {
                return ResourceManager.GetString("Product_ForOneMac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For one PC.
        /// </summary>
        public static string Product_ForOnePc {
            get {
                return ResourceManager.GetString("Product_ForOnePc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For up to three Macs.
        /// </summary>
        public static string Product_ForUptoThreeMacs {
            get {
                return ResourceManager.GetString("Product_ForUptoThreeMacs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For up to three PCs.
        /// </summary>
        public static string Product_ForUptoThreePcs {
            get {
                return ResourceManager.GetString("Product_ForUptoThreePcs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For up to two Macs.
        /// </summary>
        public static string Product_ForUptoTwoMacs {
            get {
                return ResourceManager.GetString("Product_ForUptoTwoMacs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For up to two PCs.
        /// </summary>
        public static string Product_ForUptoTwoPcs {
            get {
                return ResourceManager.GetString("Product_ForUptoTwoPcs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License type:.
        /// </summary>
        public static string Product_LicenseTypeColon {
            get {
                return ResourceManager.GetString("Product_LicenseTypeColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of stock.
        /// </summary>
        public static string Product_OutOfStock {
            get {
                return ResourceManager.GetString("Product_OutOfStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Product_PdpTabsHeaderDefault {
            get {
                return ResourceManager.GetString("Product_PdpTabsHeaderDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-Order.
        /// </summary>
        public static string Product_Preorder {
            get {
                return ResourceManager.GetString("Product_Preorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-order now.
        /// </summary>
        public static string Product_PreOrderNow {
            get {
                return ResourceManager.GetString("Product_PreOrderNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string Product_PriceFrom {
            get {
                return ResourceManager.GetString("Product_PriceFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now.
        /// </summary>
        public static string Product_PriceNow {
            get {
                return ResourceManager.GetString("Product_PriceNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now:.
        /// </summary>
        public static string Product_PriceNowColon {
            get {
                return ResourceManager.GetString("Product_PriceNowColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Product_PriceSave {
            get {
                return ResourceManager.GetString("Product_PriceSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save:.
        /// </summary>
        public static string Product_PriceSaveColon {
            get {
                return ResourceManager.GetString("Product_PriceSaveColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting at.
        /// </summary>
        public static string Product_PriceStartingAt {
            get {
                return ResourceManager.GetString("Product_PriceStartingAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to was.
        /// </summary>
        public static string Product_PriceWas {
            get {
                return ResourceManager.GetString("Product_PriceWas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to was:.
        /// </summary>
        public static string Product_PriceWasColon {
            get {
                return ResourceManager.GetString("Product_PriceWasColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product not available.
        /// </summary>
        public static string Product_ProductNotAvailable {
            get {
                return ResourceManager.GetString("Product_ProductNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity:.
        /// </summary>
        public static string Product_QuantityColon {
            get {
                return ResourceManager.GetString("Product_QuantityColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        public static string Product_QuantityShort {
            get {
                return ResourceManager.GetString("Product_QuantityShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty:.
        /// </summary>
        public static string Product_QuantityShortColon {
            get {
                return ResourceManager.GetString("Product_QuantityShortColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUICK VIEW.
        /// </summary>
        public static string Product_QuickView {
            get {
                return ResourceManager.GetString("Product_QuickView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release date:.
        /// </summary>
        public static string Product_ReleaseDateColon {
            get {
                return ResourceManager.GetString("Product_ReleaseDateColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Product_Remove {
            get {
                return ResourceManager.GetString("Product_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review and checkout.
        /// </summary>
        public static string Product_ReviewAndCheckout {
            get {
                return ResourceManager.GetString("Product_ReviewAndCheckout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop this product.
        /// </summary>
        public static string Product_ShopThisProduct {
            get {
                return ResourceManager.GetString("Product_ShopThisProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sold out.
        /// </summary>
        public static string Product_SoldOut {
            get {
                return ResourceManager.GetString("Product_SoldOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student price.
        /// </summary>
        public static string Product_StudentPrice {
            get {
                return ResourceManager.GetString("Product_StudentPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View instructions.
        /// </summary>
        public static string Product_ViewInstructions {
            get {
                return ResourceManager.GetString("Product_ViewInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAVE.
        /// </summary>
        public static string Product_YouSave {
            get {
                return ResourceManager.GetString("Product_YouSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship it.
        /// </summary>
        public static string ProductDeliveryMethods_Physical {
            get {
                return ResourceManager.GetString("ProductDeliveryMethods_Physical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Shipping on orders over $49.99.
        /// </summary>
        public static string ProductDetailPage_FreeShipping {
            get {
                return ResourceManager.GetString("ProductDetailPage_FreeShipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by keyword.
        /// </summary>
        public static string SearchPartViewModel_SearchFieldPlaceholder {
            get {
                return ResourceManager.GetString("SearchPartViewModel_SearchFieldPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No more products were found..
        /// </summary>
        public static string SearchResultViewModel_NoMoreProductsFound {
            get {
                return ResourceManager.GetString("SearchResultViewModel_NoMoreProductsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . Please check your search criteria and try again..
        /// </summary>
        public static string SearchResultViewModel_NoProductsFoundPost {
            get {
                return ResourceManager.GetString("SearchResultViewModel_NoProductsFoundPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results were found for: .
        /// </summary>
        public static string SearchResultViewModel_NoProductsFoundPre {
            get {
                return ResourceManager.GetString("SearchResultViewModel_NoProductsFoundPre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid promo code.
        /// </summary>
        public static string ShoppingCart_AddCouponFailed {
            get {
                return ResourceManager.GetString("ShoppingCart_AddCouponFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add coupon to shopping cart.
        /// </summary>
        public static string ShoppingCart_AddCouponInvalidCoupon {
            get {
                return ResourceManager.GetString("ShoppingCart_AddCouponInvalidCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add coupon to shopping cart. Coupon code has already been used.
        /// </summary>
        public static string ShoppingCart_AddCouponInvalidCouponAlreadyUsed {
            get {
                return ResourceManager.GetString("ShoppingCart_AddCouponInvalidCouponAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add coupon to shopping cart. Coupon code is not valid.
        /// </summary>
        public static string ShoppingCart_AddCouponInvalidCouponCode {
            get {
                return ResourceManager.GetString("ShoppingCart_AddCouponInvalidCouponCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add coupon to shopping cart. Coupon code does not exist.
        /// </summary>
        public static string ShoppingCart_AddCouponInvalidCouponNotExists {
            get {
                return ResourceManager.GetString("ShoppingCart_AddCouponInvalidCouponNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add coupon to shopping cart. Offer has hit its limit and the coupon code is no longer available.
        /// </summary>
        public static string ShoppingCart_AddCouponInvalidCouponOfferHitItsLimit {
            get {
                return ResourceManager.GetString("ShoppingCart_AddCouponInvalidCouponOfferHitItsLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add coupon to shopping cart. Offer associated to this coupon is not live.
        /// </summary>
        public static string ShoppingCart_AddCouponInvalidCouponOfferNotYetLive {
            get {
                return ResourceManager.GetString("ShoppingCart_AddCouponInvalidCouponOfferNotYetLive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add coupon to shopping cart. Shopper has already used a coupon for this offer.
        /// </summary>
        public static string ShoppingCart_AddCouponInvalidCouponOfferUsedByShopper {
            get {
                return ResourceManager.GetString("ShoppingCart_AddCouponInvalidCouponOfferUsedByShopper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add coupon to shopping cart. Session the coupon was applied to has expired.
        /// </summary>
        public static string ShoppingCart_AddCouponInvalidCouponSessionExpired {
            get {
                return ResourceManager.GetString("ShoppingCart_AddCouponInvalidCouponSessionExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re sorry but your shopping cart is locked.
        /// </summary>
        public static string ShoppingCart_AddProductCartLocked {
            get {
                return ResourceManager.GetString("ShoppingCart_AddProductCartLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re sorry but we were unable to add the product to the cart..
        /// </summary>
        public static string ShoppingCart_AddProductFailed {
            get {
                return ResourceManager.GetString("ShoppingCart_AddProductFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re sorry but the product is currently out of stock and cannot be added to your cart..
        /// </summary>
        public static string ShoppingCart_AddProductOutOfStock {
            get {
                return ResourceManager.GetString("ShoppingCart_AddProductOutOfStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re sorry but we were unable to update your item..
        /// </summary>
        public static string ShoppingCart_ChangeVariationFailed {
            get {
                return ResourceManager.GetString("ShoppingCart_ChangeVariationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the product.
        /// </summary>
        public static string ShoppingCart_ChangeVariationGenericProduct {
            get {
                return ResourceManager.GetString("ShoppingCart_ChangeVariationGenericProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re sorry but {0} is currently out of stock and cannot be added to your cart..
        /// </summary>
        public static string ShoppingCart_ChangeVariationProductOutOfStock {
            get {
                return ResourceManager.GetString("ShoppingCart_ChangeVariationProductOutOfStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may only have one active subscription..
        /// </summary>
        public static string ShoppingCart_CheckEligibilityExistingSharedSubscriptionError {
            get {
                return ResourceManager.GetString("ShoppingCart_CheckEligibilityExistingSharedSubscriptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has been added to your cart..
        /// </summary>
        public static string ShoppingCart_ItemAddedToCart {
            get {
                return ResourceManager.GetString("ShoppingCart_ItemAddedToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re sorry but we were unable to update your item..
        /// </summary>
        public static string ShoppingCart_UpdateLineItemFailed {
            get {
                return ResourceManager.GetString("ShoppingCart_UpdateLineItemFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re sorry but we were unable to update shipping method..
        /// </summary>
        public static string ShoppingCart_UpdateShippingFailed {
            get {
                return ResourceManager.GetString("ShoppingCart_UpdateShippingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View cart.
        /// </summary>
        public static string ShoppingCart_ViewCart {
            get {
                return ResourceManager.GetString("ShoppingCart_ViewCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout.
        /// </summary>
        public static string ShoppingCartViewModel_ButtonCheckoutNormal {
            get {
                return ResourceManager.GetString("ShoppingCartViewModel_ButtonCheckoutNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by:.
        /// </summary>
        public static string SortCategory_SortByColon {
            get {
                return ResourceManager.GetString("SortCategory_SortByColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name (A to Z).
        /// </summary>
        public static string SortCategory_SortChoiceNameAsc {
            get {
                return ResourceManager.GetString("SortCategory_SortChoiceNameAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name (Z to A).
        /// </summary>
        public static string SortCategory_SortChoiceNameDesc {
            get {
                return ResourceManager.GetString("SortCategory_SortChoiceNameDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price (low to high).
        /// </summary>
        public static string SortCategory_SortChoicePriceAsc {
            get {
                return ResourceManager.GetString("SortCategory_SortChoicePriceAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price (high to low).
        /// </summary>
        public static string SortCategory_SortChoicePriceDesc {
            get {
                return ResourceManager.GetString("SortCategory_SortChoicePriceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top sellers.
        /// </summary>
        public static string SortCategory_SortChoiceTopSellers {
            get {
                return ResourceManager.GetString("SortCategory_SortChoiceTopSellers", resourceCulture);
            }
        }
    }
}
